# Created by: Eric McCorkle <eric@metricspace.net>
# $FreeBSD$

PORTNAME=	libxslt
PORTVERSION=	1.1.28
DISTVERSIONSUFFIX=	-5.el7
CATEGORIES=	textproc linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	The XSLT C library for GNOME (Linux CentOS ${LINUX_DIST_VER})

LICENSE=	MIT

USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
