# $FreeBSD$

PORTNAME=	xbyak
PORTVERSION=	5.40
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

COMMENT=	C++-based JIT assembler for X86 architectures

LICENSE=	BSD

USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	herumi
GH_PROJECT=	xbyak

.include <bsd.port.mk>
