# $FreeBSD$

PORTNAME=	ate-pairing
PORTVERSION=	1.2
DISTVERSIONPREFIX=	v
CATEGORIES=	math

COMMENT=	High-Speed Implementation of Optimal ATE Pairing over BN Curves

LICENSE=	BSD

LIB_DEPENDS=	libgmp.so:math/gmp

USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	herumi
GH_PROJECT=	ate-pairing

.include <bsd.port.mk>
